// SelectFolder.h

#pragma once

#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>

#include "Ascii.h"
#include "Common.h"

#include "Registry.h"

#define SELECT_FOLDER_WINDOW_CLASS_NAME											"Main SelectFolder Window Class"

#define SELECT_FOLDER_WINDOW_CLASS_STYLE										0
#define SELECT_FOLDER_WINDOW_CLASS_ICON											LoadIcon( NULL, IDI_APPLICATION )
#define SELECT_FOLDER_WINDOW_CLASS_CURSOR										LoadCursor( NULL, IDC_ARROW )
#define SELECT_FOLDER_WINDOW_CLASS_BACKGROUND_COLOR								COLOR_WINDOW
#define SELECT_FOLDER_WINDOW_CLASS_BACKGROUND									( HBRUSH )( SELECT_FOLDER_WINDOW_CLASS_BACKGROUND_COLOR + 1 )
#define SELECT_FOLDER_WINDOW_CLASS_MENU_NAME									NULL

#define SELECT_FOLDER_WINDOW_EXTENDED_STYLE										( WS_EX_TOOLWINDOW | WS_EX_TOPMOST )
#define SELECT_FOLDER_WINDOW_DEFAULT_TITLE										"Select Folder"
#define SELECT_FOLDER_WINDOW_STYLE												( WS_POPUP | WS_BORDER )

#define SELECT_FOLDER_WINDOW_SEPARATOR_SIZE										10

#define SELECT_FOLDER_WINDOW_DEFAULT_LEFT										100
#define SELECT_FOLDER_WINDOW_DEFAULT_TOP										100

// Note that input box window width and height are defined further down,
// as these are calculated from some of the following values

#define SELECT_FOLDER_TITLE_WINDOW_CLASS_NAME									WC_STATIC
#define SELECT_FOLDER_TITLE_WINDOW_EXTENDED_STYLE								0
#define SELECT_FOLDER_TITLE_WINDOW_STYLE										( WS_CHILD | WS_VISIBLE )
#define SELECT_FOLDER_TITLE_WINDOW_HEIGHT										13

#define SELECT_FOLDER_TREE_VIEW_WINDOW_CLASS_NAME								WC_TREEVIEW
#define SELECT_FOLDER_TREE_VIEW_WINDOW_EXTENDED_STYLE							0
#define SELECT_FOLDER_TREE_VIEW_WINDOW_STYLE									( WS_CHILD | WS_VISIBLE | WS_BORDER | TVS_HASBUTTONS | TVS_HASLINES | TVS_LINESATROOT )
#define SELECT_FOLDER_TREE_VIEW_WINDOW_HEIGHT									100
#define SELECT_FOLDER_TREE_VIEW_WINDOW_DUMMY_ITEM_TEXT							"<dummy>"

#define SELECT_FOLDER_BUTTON_WINDOW_CLASS_NAME									WC_BUTTON
#define SELECT_FOLDER_BUTTON_WINDOW_EXTENDED_STYLE								0
#define SELECT_FOLDER_BUTTON_WINDOW_STYLE										( WS_CHILD | WS_VISIBLE | BS_FLAT | BS_VCENTER )

#define SELECT_FOLDER_BUTTON_WINDOW_WIDTH										50
#define SELECT_FOLDER_BUTTON_WINDOW_HEIGHT										20

#define SELECT_FOLDER_OK_BUTTON_WINDOW_TEXT										"OK"
#define SELECT_FOLDER_CANCEL_BUTTON_WINDOW_TEXT									"Cancel"

#define SELECT_FOLDER_OK_BUTTON_WINDOW_ID										WM_USER
#define SELECT_FOLDER_CANCEL_BUTTON_WINDOW_ID									( WM_USER + 1 )

#define SELECT_FOLDER_REGISTRY_TOP_LEVEL_KEY									HKEY_CURRENT_USER
#define SELECT_FOLDER_REGISTRY_SUB_KEY											"Software\\Jim Smith\\SelectFolder"
#define SELECT_FOLDER_REGISTRY_LEFT_VALUE_NAME									"Left"
#define SELECT_FOLDER_REGISTRY_TOP_VALUE_NAME									"Top"

#define SELECT_FOLDER_WINDOW_WIDTH												300
#define SELECT_FOLDER_WINDOW_HEIGHT												( WINDOW_BORDER_HEIGHT + SELECT_FOLDER_WINDOW_SEPARATOR_SIZE + SELECT_FOLDER_TITLE_WINDOW_HEIGHT + SELECT_FOLDER_WINDOW_SEPARATOR_SIZE + SELECT_FOLDER_TREE_VIEW_WINDOW_HEIGHT + SELECT_FOLDER_WINDOW_SEPARATOR_SIZE + SELECT_FOLDER_BUTTON_WINDOW_HEIGHT + SELECT_FOLDER_WINDOW_SEPARATOR_SIZE + WINDOW_BORDER_HEIGHT )

#define UNABLE_TO_CREATE_SELECT_FOLDER_WINDOW_ERROR_MESSAGE						"Unable to create input box window"
#define UNABLE_TO_REGISTER_SELECT_FOLDER_WINDOW_CLASS_ERROR_MESSAGE				"Unable to register input box window class"

int TreeViewWindowAddDrives();

int TreeViewWindowAddSubFolders( HTREEITEM htiParentFolder );

int TreeViewWindowDeleteAllSubItems( HTREEITEM htiParentItem );

BOOL TreeViewWindowExpandItem( HTREEITEM htiItem );

BOOL TreeViewWindowGetItemPath( HTREEITEM htiItem, LPTSTR lpszItemPath );

BOOL TreeViewWindowGetItemPath( LPTSTR lpszItemPath );

BOOL TreeViewWindowGetItemText( HTREEITEM htiItem, LPTSTR lpszItemText );

BOOL TreeViewWindowInit();

BOOL SelectFolder( HWND hWndParent, LPTSTR lpszFolderPath, LPCTSTR lpszTitle = SELECT_FOLDER_WINDOW_DEFAULT_TITLE );
